apiVersion: v2
dependencies:
- condition: orion-ld.deploymentEnabled
  name: orion-ld
  repository: file://./charts/orion-ld
  version: 1.2.6
- condition: keycloak.deploymentEnabled
  name: keycloak
  repository: file://./charts/keycloak
  version: 13.0.4
- condition: credentials-config-service.deploymentEnabled
  name: credentials-config-service
  repository: file://./charts/credentials-config-service
  version: 0.0.4
- condition: contract-management.deploymentEnabled
  name: contract-management
  repository: file://./charts/contract-management
  version: 0.5.0
- condition: kong.deploymentEnabled
  name: kong
  repository: file://./charts/kong
  version: 2.8.0
- condition: mongodb.deploymentEnabled
  name: mongodb
  repository: file://./charts/mongodb
  version: 0.1.0
- condition: dsba-pdp.deploymentEnabled
  name: dsba-pdp
  repository: file://./charts/dsba-pdp
  version: 0.0.16
- condition: verifier.deploymentEnabled
  name: verifier
  repository: file://./charts/verifier
  version: 1.0.22
- condition: postgres.deploymentEnabled
  name: postgres
  repository: file://./charts/postgres
  version: 12.1.13
- condition: activation-service.deploymentEnabled
  name: activation-service
  repository: file://./charts/activation-service
  version: 2.3.1
- condition: vcwaltid.deploymentEnabled
  name: vcwaltid
  repository: file://./charts/vcwaltid
  version: 0.0.17
- condition: trusted-issuers-list.deploymentEnabled
  name: trusted-issuers-list
  repository: file://./charts/trusted-issuers-list
  version: 0.5.3
- condition: tm-forum-api.deploymentEnabled
  name: tm-forum-api
  repository: file://./charts/tm-forum-api
  version: 0.5.3
- condition: keyrock.deploymentEnabled
  name: keyrock
  repository: file://./charts/keyrock
  version: 0.7.4
- condition: mysql.deploymentEnabled
  name: mysql
  repository: file://./charts/mysql
  version: 9.4.4
- condition: mysql.deploymentEnabled
  name: wallet
  repository: file://./charts/wallet
  version: 0.1.0
description: Pruebas Pablo
name: data-space-connector
type: application
version: 3.0.7
