apiVersion: v2
appVersion: 1.0.0
dependencies:
- name: dsba-pdp
  repository: https://fiware.github.io/helm-charts
  version: 0.0.16
description: Chart holder for argo-cd
name: dsba-pdp
type: application
version: 0.0.16
