apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallet
  labels:
    app: wallet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wallet
  template:
    metadata:
      labels:
        app: wallet
    spec:
      containers:
      - name: ssi-core-dev-env
        image: pablomarrtinez/wallet:v2.1
        command: ["/bin/sh", "-c"]
        args: 
          - |
            echo '127.0.0.1 umu-verifier umu-issuer umu-webWallet' >> /etc/hosts
            /app/scripts/replace_ports.sh /app/src/main/resources/static/
            /app/ssikit.sh build-st
            /app/ssikit.sh fullApi
            tail -f
        env:
        - name: ISSUER_PORT
          value: "30011"
        - name: VERIFIER_PORT
          value: "30012"
        - name: WALLET_PORT
          value: "30013"
        - name: PEER_ENDPOINT
          value: "192.168.1.1"
        ports:
        - containerPort: 30011
        - containerPort: 30012
        - containerPort: 30013

