apiVersion: v2
name: fiware-platform
description: Helm chart to deploy the FIWARE Data pace Connector
type: application
version: 5.5.5
maintainers:
  - name: Dennis Wendland
    email: dennis.wendland@fiware.org
dependencies:
  - name: vcwaltid
    version: 0.0.16
    repository: file://./charts/walt-id
    condition: vcwaltid.deploymentEnabled
