apiVersion: v1
appVersion: 0.3.2
description: A Helm chart for running the dsba-pdp on kubernetes.
icon: https://fiware.github.io/catalogue/img/fiware.png
keywords:
- fiware
- dsba
- verifiablecredentials
- ssi
- pdp
maintainers:
- email: stefan.wiedemann@fiware.org
  name: wistefan
name: dsba-pdp
sources:
- https://github.com/wistefan/dsba-pdp
version: 0.0.16
