apiVersion: v2
appVersion: 0.13.2
dependencies:
- name: tm-forum-api
  repository: https://fiware.github.io/helm-charts
  version: 0.5.3
description: Chart holder for argo-cd
name: tm-forum-api
type: application
version: 0.5.3
