apiVersion: v1
kind: Service
metadata:
  name:  {{ .Release.Name }}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 80 # El puerto externo
      targetPort: {{ .Values.pep-pdp.containerPort }} # El puerto del contenedor

