apiVersion: v1
appVersion: 0.0.1
description: A Helm chart for running the i4Trust DSBA vcwaltid.
home: https://github.com/hesusruiz/vcwaltid
keywords:
- i4Trust
- experimentation framework
- proof of concept
- verifiable credentials
maintainers:
- email: stefan.wiedemann@fiware.org
  name: wistefan
name: vcwaltid
version: 0.0.17
