apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallet-ssikit
  labels:
    app: wallet-ssikit
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: wallet-ssikit
  template:
    metadata:
      labels:
        app: wallet-ssikit
    spec:
      containers:
      - name: ssi-core-dev-env
        image: pablomarrtinez/wallet:v3.0.3
        command: ["/bin/sh", "-c"]
        args: 
          - |
            echo '127.0.0.1 umu-verifier umu-issuer umu-webWallet' >> /etc/hosts
            /app/ssikit.sh fullApi
            tail -f
        env:
        - name: ISSUER_PORT
          value: "30400"
        - name: VERIFIER_PORT
          value: "30401"
        - name: WALLET_PORT
          value: "30402"
        - name: PEER_ENDPOINT
          value: "{{ .Values.FABRIC_ENDPOINT }}"
        - name: MODE
          value: "Default"
        - name: LOCAL
          value: "true"
        ports:
        - containerPort: 30400
        - containerPort: 30401
        - containerPort: 30402
