apiVersion: v2
appVersion: 4.4.12
dependencies:
- name: mongodb
  repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
  version: 11.0.4
description: Chart holder for argo-cd
name: mongodb
type: application
version: 0.1.0
