apiVersion: v1
appVersion: 8.3.3
description: A Helm chart for running the fiware idm keyrock on kubernetes.
home: https://fiware-idm.readthedocs.io/en/latest/
icon: https://fiware.github.io/catalogue/img/fiware.png
keywords:
- fiware
- keyrock
- idm
maintainers:
- email: stefan.wiedemann@fiware.org
  name: wistefan
- email: dennis.wendland@fiware.org
  name: dwendland
name: keyrock
sources:
- https://github.com/ging/fiware-idm
version: 0.7.5
